### ISSUE TITLE
[BUG] EqualToSnapshot takes no parameters

### ISSUE THREAD

**Issue by Marcel-B** [theramis/Snapper#49]
The function Snapper.Nunit.Is.EqualToSnapshot takes a parameter SnapshotName according to the documentation. Unfortunately I cannot use this function, only without overloading.

Operation System: Windows 10
Snapper Version: v2.2.1
Snapper.Nunit: v2.2.1
NUnit: v3.12.0
.Net Version: .NET Framework 4.7.2

![image](https://user-images.githubusercontent.com/9868657/72728047-bd8fce80-3b8c-11ea-908a-6354f95dba16.png)

**Comment by semmgeorge** [comment]
I have the same bug

**Comment by theramis** [comment]
Firstly sorry for the late reply, life has been super busy currently. 

Thanks for the bug report. 

It turns out this is an issue of outdated documentation. The `EqualToSnapshot` method used to take in a parameter in V1 but in V2 this was deprecated. 
A new method called `EqualToChildSnapshot` was made which takes in the name of a child snapshot.
See [here](https://theramis.github.io/Snapper/changelog.html#200---2019-08-14) for the changelog.

Child snapshots are a little bit different to the previous snapshot name functionality. You can read up on how child snapshots work here https://theramis.github.io/Snapper/snapper/basics.html#child-snapshots

**Comment by theramis** [comment]
Updated the docs to reflect the correct methods. 
See https://theramis.github.io/Snapper/snapper-nunit/snapper-nunit.html#basics
