### ISSUE TITLE
Custom update snapshot attributes

### ISSUE THREAD

**Issue by LaurenceJKing** [theramis/Snapper#73]
**Is your feature request related to a problem? Please describe.**
Currently, the only way to update a snapshot is via the `UpdateSnapshot` attribute (or the environment variable). Both of these solutions require changing the code, which means that if I accidently leave one or other of those set then the snapshot will be overwritten by any of my team mates who subsequently run the tests.*

**Describe the solution you'd like**
Allow users to override the `UpdateSnapshot` attribute with other behaviors (such as opening a diff window) when the snapshots do not match. I don't think that Snapper needs to provide any of those behaviors out of the box - but if we could make it more extensible then users could roll their own.

**Describe alternatives you've considered**
We are using F# and XUnit for our tests, so I considered using XUnit's `ITestOutputHelper` to write out the new snapshot, which could then be copied and pasted if necessary. However, since we are using F#, most of our tests are static rather than instance methods, so we can't use the `ITestOutputHelper`. (Well, we could, but we're keen to avoid that, because we'd rather keep a consistent style).

*I have definitely done this. I'm just going to hang my head in shame :(

**Comment by theramis** [comment]
Hey @LaurenceJKing, 

Sorry about the super late reply. 

> Currently, the only way to update a snapshot is via the UpdateSnapshot attribute (or the environment variable). Both of these solutions require changing the code.

Another possible solution which wouldn't require code is to set the `UpdateSnapshot` environment variable outside of your code (e.g. in your terminal). This way it would not get committed. Thoughts?

> Allow users to override the UpdateSnapshot attribute with other behaviors (such as opening a diff window) when the snapshots do not match. I don't think that Snapper needs to provide any of those behaviors out of the box - but if we could make it more extensible then users could roll their own.

Correct me if I'm wrong but it sounds like what you are wanting to be to able to override something like https://github.com/theramis/Snapper/blob/master/project/Snapper/Core/SnapshotUpdateDecider.cs. 

The core logic of Snapper can basically be explained in 3 steps.
1. Compare new snapshot vs old snapshot
2. Decide whether to update snapshot
3. Update or Assert snapshot

It sounds like you'd like to make step 2 customisable/extendable? Would that be correct?


Assuming I've interpreted your problem/solution correctly. If step 2 was customisable I'd be keen to hear how you would implement step 2 so that it doesn't require code changes. You mentioned a diff window, I imagine as part of the diff window you'd need like an update button too so you can tell step 3 whether to update or not.

**Comment by LaurenceJKing** [comment]
Hi @theramis,

Thanks for getting back to me.

I've been tinkering with this for a while, and I don't think my suggestion of a diff window will really work (all the tools I have come across require two files to compare - but Snapper only saves the old snapshot (which is one of the things I love about it).

Setting the environment variable from the terminal could be the way to go. Thanks.
